plugins:
  - jekyll-sitemap

# GitHub Pages Jekyll設定
title: ice458の物置き
description: ice458の製作物等を紹介するサイトです
url: https://ice458.github.io
baseurl: ""

# 除外設定（サイトマップから除外）
exclude:
  - README.md
  - "*.py"
  - "*.bat"
  - __pycache__/
  - templates/
  - "*.md"

# ビルド設定
markdown: kramdown
highlighter: rouge

# パーマリンク設定（重要: ディレクトリ形式URL対応）
permalink: pretty

# SEO設定
lang: ja
author: ice458

# デフォルト設定
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: null
      sitemap: true